### ISSUE TITLE
.Net in Jenkins

### ISSUE THREAD

**Issue by benbissett** [revaturelabs/sierra#108]
Configure .NET applications to build in Jenkins. The key to successfully making this work is to successfully configure Jenkins in an instance with Windows, because of its compatibility with MSBuild.

**Comment by jermaineanderson1995** [comment]
1. Installed Plugins: 
- MSBuild

2. Installed Tools: 
- NuGet
- MSBuild
- Git
- NET Framework 

Current Issue:
The successful build is corrupted. Keep getting "%%ERRORLEVEL%%"
