### ISSUE TITLE
Deploy Caliber Project

### ISSUE THREAD

**Issue by benbissett** [revaturelabs/sierra#109]
Figure out how to make the Caliber project appear in tomcat properly. We have the WAR built already but when we place it in tomcat we can't get the webpage to appear.

**Comment by jermaineanderson1995** [comment]
After building, the Caliber Project works in the root context. Use a script for this.
  ex. caliber.war --> ROOT.war

The projects also needs a HTTPS option where you pass your certificate or create a self-signed certificate
